name: reviewdog
on: [push, pull_request]

jobs:
  reviewdog_eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - name: Run eslint with reviewdog
        uses: reviewdog/action-eslint@v1.0.0
        with:
          eslint_flags: 'js/'